name: Cypress Tests
on: [push]
jobs:
  get-ip-address:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.set-ip.outputs.ip }}
    steps:
      - name: Set IP address
        id: set-ip
        run: echo "::set-output name=ip::$(hostname -I | cut -d' ' -f1)"

  cypress-run:
    needs: get-ip-address
    runs-on: ubuntu-latest
    env:
      RUNNER_IP_ADDRESS: ${{ needs.get-ip-address.outputs.ip }}
      
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npm test
          wait-on: 'http://${{ env.RUNNER_IP_ADDRESS }}:8081' # Waits for above
          # Records to Cypress Cloud 
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: false # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
